accounts/urls.py
from django.urls import path

from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/change_password/', ChangePasswordView.as_view(), name='user_change_password')
]

charity/urls.py
from django.urls import path

from charity.views import *

app_name = 'charity'

urlpatterns = [
    path('add_donation/', AddDonationStep1View.as_view(), name='add_donation'),
    path('add_donation/step2/', AddDonationStep2View.as_view(), name='add_donation_step2'),
    path('add_donation/step3/', AddDonationStep3View.as_view(), name='add_donation_step3'),
    path('add_donation/step4/', AddDonationStep4View.as_view(), name='add_donation_step4'),
    path('add_donation/step5/', AddDonationStep5View.as_view(), name='add_donation_step5'),
    path('add_donation/confirmation/', ConfirmationView.as_view(), name='confirmation'),
    path('pick_up/<int:pk>/', DonationTakenView.as_view(), name='donation_taken'),
    path('donation/<int:pk>/', DonationDetailView.as_view(), name='donation_detail'),

]

donate/urls.py
from django.contrib import admin
from django.urls import path, include

from charity.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='LandingPage'),
    path('', include('charity.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    donations = models.PositiveIntegerField(default=0)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.core.exceptions import ValidationError

from .models import CustomUser


class AdminCustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class AdminCustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class AddUserModelForm(forms.ModelForm):
    password1 = forms.CharField(max_length=128, widget=forms.PasswordInput, label='Hasło')
    password2 = forms.CharField(max_length=128, widget=forms.PasswordInput, label='Powtórz Hasło')

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Imię', 'last_name': 'Nazwisko', 'email': 'Email'}

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('password1') != cleaned_data.get('password2'):
            raise ValidationError('hasła nie są takie same')
        return cleaned_data


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput, label='Stare Hasło')
    new_password = forms.CharField(widget=forms.PasswordInput, label='Nowe Hasło')
    new_password_confirm = forms.CharField(widget=forms.PasswordInput, label='Powtórz Hasło')

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('password1') != cleaned_data.get('password2'):
            raise ValidationError('hasła nie są takie same')
        return cleaned_data

accounts/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from accounts.forms import *
from charity.models import Donation


# Create your views here.

class RegisterView(View):
    def get(self, request):
        form = AddUserModelForm()
        return render(request, 'accounts/register.html', {'form': form})

    def post(self, request):
        form = AddUserModelForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = form.cleaned_data['email']
            user.set_password(form.cleaned_data['password1'])
            user.save()
            return redirect('accounts:login')
        return redirect('accounts:register')


class LoginView(View):
    def get(self, request):
        return render(request, 'accounts/login.html')

    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')
        print(email, password)
        user = authenticate(request, username=email, password=password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('LandingPage')
        return redirect('accounts:register')


class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('LandingPage')


class ProfileView(LoginRequiredMixin, View):

    def get(self, request):
        donations = Donation.objects.filter(user=request.user, is_taken=False).order_by('-pick_up_date')
        donations_taken = Donation.objects.filter(user=request.user, is_taken=True).order_by('-pick_up_date')
        messages_received = messages.get_messages(request)
        message_list = list(messages_received)
        return render(request, 'accounts/profile.html', {'donations': donations,
                                                         'donations_taken': donations_taken, 'message_list': message_list})


class ChangePasswordView(LoginRequiredMixin, View):
    def get(self, request):
        form = ChangePasswordForm()
        messages_received = messages.get_messages(request)
        message_list = list(messages_received)
        return render(request, 'accounts/user_change_password.html', {'form': form,
                                                                      'message_list': message_list})

    def post(self, request):
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password']
            new_password_confirm = form.cleaned_data['new_password_confirm']
            if request.user.check_password(old_password):
                if new_password == new_password_confirm:
                    request.user.set_password(new_password)
                    request.user.save()
                    update_session_auth_hash(request, request.user)
                    messages.success(request, 'Hasło zostało zmienione.')
                    return redirect('accounts:profile')
                else:
                    messages.error(request, 'Nowe hasła nie pasują do siebie.')
            else:
                messages.error(request, 'Nieprawidłowe stare hasło.')
        return redirect('accounts:user_change_password')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
  <body>
    <header>
      {% include 'navbar.html' %}
    </header>

    <section class="login-page">
      <h2>Zaloguj się</h2>
      <form method="post">
          {% csrf_token %}
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
          <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'accounts:register' %}" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zaloguj się</button> 
        </div>
      </form>
    </section>
  {% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
  <body>
    <header>
      {% include 'navbar.html' %}
    </header>

    <section class="login-page">
        <h2>{% if message_list %}{% for message in message_list %}{{ message }}{% endfor %}
      {% else %}PROFIL{% endif %}</h2>
      <h1>Imie: {{ user.first_name }}</h1>
        <h1>Nazwisko: {{ user.last_name }}</h1>
        <h1>Email: {{ user.email }}</h1>
        {% if donations or donations_taken %}
            <p style="font-size: 18px;"> Lista darów:</p>
        <ul>
        {% for donation in donations %}
            <li style="font-size: 18px;">{{ donation.bags }} worków dla {{ donation.institution.name }}
            ({% for category in donation.categories.all %}{{ category.name }}{% if not forloop.last %}, {% endif %}{% endfor %})
            </li>
            <ul><li style="font-size: 18px;">
                Odbiór: {{ donation.pick_up_date }} o godzinie {{ donation.pick_up_time }} -
                <a href="{% url 'charity:donation_taken' donation.id %}" class="btn btn--small btn--without-border active">Oznacz jako odebraną</a>
                <a href="{% url 'charity:donation_detail' donation.id %}" class="btn btn--small btn--without-border active">Szczegóły</a>
            </li></ul>

        {% endfor %}
                {% for donation in donations_taken %}
            <li style="font-size: 18px; ; color: darkgreen;">{{ donation.bags }} worków dla {{ donation.institution.name }}
            ({% for category in donation.categories.all %}{{ category.name }}{% if not forloop.last %}, {% endif %}{% endfor %})
            </li>
            <ul><li style="font-size: 18px; ; color: darkgreen;">
                Odedbrano: {{ donation.taken_date }} o godzinie {{ donation.taken_time }}
                <a href="{% url 'charity:donation_detail' donation.id %}" class="btn btn--small btn--without-border active">Szczegóły</a>
            </li></ul>

        {% endfor %}

        </ul>
        {% endif %}
    </section>
  {% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <header>
      {% include 'navbar.html' %}
    </header>

    <section class="login-page">
      <h2>Załóż konto</h2>
      <form method="post">
          {% csrf_token %}
          {% for field in form %}
        <div class="form-group">
          <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" placeholder="{{ field.label }}" />
        </div>
          {% endfor %}


        <div class="form-group form-group--buttons">
          <a href="{% url 'accounts:login' %}" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>

  </body>
</html>
{% endblock %}

accounts/templates/accounts/user_change_password.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
  <body>
    <header>
      {% include 'navbar.html' %}
    </header>

    <section class="login-page">
      <h2>{% if message_list %}{% for message in message_list %}{{ message }}{% endfor %}
      {% else %}Zmień Hasło{% endif %}</h2>
      <form method="post">
          {% csrf_token %}
          {% for field in form %}
        <div class="form-group">
          <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" placeholder="{{ field.label }}" />
        </div>
          {% endfor %}


        <div class="form-group form-group--buttons">
          <button class="btn" type="submit">Potwierdź</button>
        </div>
      </form>
    </section>
  {% endblock %}