accounts/urls.py
from django.urls import path

from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/change_password/', ChangePasswordView.as_view(), name='user_change_password')
]

charity/urls.py
from django.urls import path

from charity.views import *

app_name = 'charity'

urlpatterns = [
    path('add_donation/', AddDonationStep1View.as_view(), name='add_donation'),
    path('add_donation/step2/', AddDonationStep2View.as_view(), name='add_donation_step2'),
    path('add_donation/step3/', AddDonationStep3View.as_view(), name='add_donation_step3'),
    path('add_donation/step4/', AddDonationStep4View.as_view(), name='add_donation_step4'),
    path('add_donation/step5/', AddDonationStep5View.as_view(), name='add_donation_step5'),
    path('add_donation/confirmation/', ConfirmationView.as_view(), name='confirmation'),
    path('pick_up/<int:pk>/', DonationTakenView.as_view(), name='donation_taken'),
    path('donation/<int:pk>/', DonationDetailView.as_view(), name='donation_detail'),

]

donate/urls.py
from django.contrib import admin
from django.urls import path, include

from charity.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='LandingPage'),
    path('', include('charity.urls')),
    path('accounts/', include('accounts.urls'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href={% static "css/style.css" %} />
  </head>
  <body>
  {% block content %}

  {% endblock %}
<footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
          <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>

          <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2023</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"><img src={% static "images/icon-facebook.svg" %}/></a>
          <a href="#" class="btn btn--small"><img src={% static "images/icon-instagram.svg" %}/></a>
        </div>
      </div>
    </footer>

    <script src={% static 'js/app.js' %}></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <header class="header--main-page">
     {% include 'navbar.html' %}

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Zacznij pomagać!<br />
            Oddaj niechciane rzeczy w zaufane ręce
          </h1>
        </div>
      </div>
    </header>
    <section id="stats" class="stats">
      <div class="container container--85">
        <div class="stats--item">
          <em>{% if bags_quantity is None %}0{% else %}{{ bags_quantity }}{% endif %}</em>
          <h3>Oddanych worków</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
        </div>

        <div class="stats--item">
          <em>5</em>
          <h3>Wspartych organizacji</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
        </div>

      </div>
    </section>

    <section id="steps" class="steps">
      <h2>Wystarczą 4 proste kroki</h2>

      <div class="steps--container">
        <div class="steps--item">
          <span class="icon icon--hands"></span>
          <h3>Wybierz rzeczy</h3>
          <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--arrow"></span>
          <h3>Spakuj je</h3>
          <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--glasses"></span>
          <h3>Zdecyduj komu chcesz pomóc</h3>
          <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--courier"></span>
          <h3>Zamów kuriera</h3>
          <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
      </div>

      <a href="{% url 'accounts:register' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
      <div class="about-us--text">
        <h2>O nas</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
        <img src={% static "images/signature.svg" %} class="about-us--text-signature" alt="Signature" />
      </div>
      <div class="about-us--image"><img src={% static "images/about-us.jpg" %} alt="People in circle" /></div>
    </section>

     <section id="help" class="help">
      <h2>Komu pomagamy?</h2>

      <ul class="help--buttons">
        <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
        <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
        <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
      </ul>

      <!-- SLIDE 1 -->
      <div class="help--slides active" data-id="1">
        <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>

        <ul class="help--slides-items">
            {% for foundation in foundations %}
                <li>
            <div class="col">
              <div class="title">Fundacja "{{ foundation.name}}"</div>
              <div class="subtitle">Cel i misja: {{ foundation.description}}</div>
            </div>

            <div class="col"><div class="text">{% for category in foundation.categories.all %}
                {{ category.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</div></div>
          </li>
            {% endfor %}
        </ul>
        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
        </ul>
        -->
      </div>


      <!-- SLIDE 2 -->
      <div class="help--slides" data-id="2">
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
          quos suscipit corporis!
        </p>
         <ul class="help--slides-items">
            {% for ngo in ngos %}
                <li>
            <div class="col">
              <div class="title">Organizacja "{{ ngo.name}}"</div>
              <div class="subtitle">Cel i misja: {{ ngo.description}}</div>
            </div>

            <div class="col"><div class="text">{% for category in ngo.categories.all %}
                {{ category.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</div></div>
          </li>
            {% endfor %}
        </ul>

        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
        </ul>
        -->
      </div>

      <!-- SLIDE 3 -->
      <div class="help--slides" data-id="3">
        <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
         <ul class="help--slides-items">
            {% for local in locals %}
                <li>
            <div class="col">
              <div class="title">Lokalna zbiórka "{{ local.name}}"</div>
              <div class="subtitle">Cel i misja: {{ local.description}}</div>
            </div>

            <div class="col"><div class="text">{% for category in local.categories.all %}
                {{ category.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</div></div>
          </li>
            {% endfor %}
        </ul>

        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
        </ul>
        -->
      </div>
    </section>

{% endblock %}

templates/navbar.html
      <nav class="container container--70">
          {% if user.is_authenticated %}
        <ul class="nav--actions">
          <li class="logged-user">
            Witaj {{ user.first_name }}
            <ul class="dropdown">
              <li><a href="{% url 'accounts:profile' %}">Profil</a></li>
              <li><a href="{% url 'accounts:user_change_password' %}">Ustawienia</a></li>
                {% if user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}">Panel Administarcyjny</a></li>
                {% endif %} 
              <li><a href="{% url 'accounts:logout' %}">Wyloguj</a></li>
            </ul>
          </li>
        </ul>
              {% else %}
              <ul class="nav--actions">
          <li><a href="{% url 'accounts:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
          <li><a href="{% url 'accounts:register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        </ul>
          {% endif %}

        <ul>
          <li><a href="{% url 'LandingPage' %}" class="btn btn--without-border active">Start</a></li>
          <li><a href="{% url 'LandingPage' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="{% url 'LandingPage' %}#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="{% url 'LandingPage' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="{% url 'charity:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="{% url 'LandingPage' %}#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>